<script src="{{ base_url('assets/js/jquery.js') }}"></script>
<script src="{{ base_url('assets/js/jquery-migrate.js') }}"></script>
<script src="{{ base_url('assets/js/bootstrap.js') }}"></script>
<script src="{{ base_url('assets/js/flexslider.js') }}"></script>
<script src="{{ base_url('assets/js/sticky.js') }}"></script>
<script src="{{ base_url('assets/js/colorbox.js') }}"></script>
<script src="{{ base_url('assets/js/bxslider.js'}}"></script>
<script src="{{ base_url('assets/js/owl-carousel.js') }}"></script>
<script src="{{ base_url('assets/js/parallax.js') }}"></script>
<script src="{{ base_url('assets/js/waypoints.js') }}"></script>
<script src="{{ base_url('assets/js/masonry.js') }}"></script>
<script src="{{ base_url('assets/js/twitter.js') }}"></script>
<script src="{{ base_url('assets/js/scriptcontact.js') }}"></script>
<script src="{{ base_url('assets/js/retina.js') }}"></script>
<script src="{{ base_url('assets/js/scripts.js') }}"></script>
